name: .NET

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: FridgetoTable
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MyRecipeManager.Web
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./MyRecipeManager.Web
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./MyRecipeManager.Web
    - name: .net publish
      run: dotnet publish -c Release -o myapp
      working-directory: ./MyRecipeManager.Web
    - name: deploy to azure app service
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './myapp'
